name: Frigate (rockchip) Beta
version: 0.16.0-beta3-rk
panel_icon: "mdi:cctv"
panel_title: Frigate
slug: frigate-rockchip
description: NVR with realtime local object detection for IP cameras
url: "https://github.com/blakeblackshear/frigate"
image: ghcr.io/blakeblackshear/frigate
startup: application
boot: auto
init: false
webui: "http://[HOST]:[PORT:5000]/"
watchdog: "http://[HOST]:[PORT:5000]/"
ingress: true
ingress_port: 5000
ingress_entry: /
panel_admin: false
homeassistant_api: true
hassio_api: true
ports:
  8555/tcp: 8555
  8555/udp: 8555
  8554/tcp: null
  8971/tcp: null
  5000/tcp: null
  1984/tcp: null
  1935/tcp: null
ports_description:
  8555/tcp: WebRTC over tcp
  8555/udp: WebRTC over udp
  8554/tcp: RTSP Restream
  8971/tcp: Authenticated Web interface
  5000/tcp: Unauthenticated Web interface (not required for Home Assistant Ingress)
  1984/tcp: go2rtc API
host_network: false
tmpfs: true
usb: true
video: true
full_access: true
privileged:
  - BPF
  - DAC_READ_SEARCH
  - IPC_LOCK
  - NET_ADMIN
  - NET_RAW
  - PERFMON
  - SYS_ADMIN
  - SYS_MODULE
  - SYS_NICE
  - SYS_PTRACE
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_TIME
schema:
  plus_api_key: password?
services:
  - "mqtt:want"
arch:
  - aarch64
map:
  - "media:rw"
  - "ssl"
  - "addon_config:rw"
  # Mount old config dir to be migrated by the image
  - "homeassistant_config:rw"
